### ISSUE TITLE
API version 0.5.3 release

### ISSUE THREAD

**Issue by insertish** [revolt-chat/status#22]
For https://github.com/revoltchat/revolt/issues/322#issuecomment-1120176609.

https://staging.revolt.chat will remain open and can be used as an 'ephermal' chat of sorts.

### [Update timeline is available here](https://github.com/revoltchat/revolt/issues/322#issuecomment-1120176609).

**Comment by Rahul-Imran** [comment]
:trollface:

**Comment by insertish** [comment]
Backup complete, starting soon.

**Comment by insertish** [comment]
Rescaling and upgrading API now.

**Comment by insertish** [comment]
Everything up since 19:23 BST.
